import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Particles from "./particles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Particles
        // className="absolute inset-0 -z-20 animate-fade-in"
        // quantity={200}
        // staticity={30}
        // ease={30}
        />
      </body>
    </html>
  );
}
